# Generated by Django 2.0.3 on 2018-03-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180312_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBoth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('registration.student',),
        ),
    ]
