# Generated by Django 2.0.3 on 2018-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_studentboth'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='attend_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='has_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Application_reason',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_referral',
            field=models.CharField(default='Nothing', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_occupation',
            field=models.TextField(default='Nothing'),
        ),
    ]
